export const INTERESTS_DATA = [
  // Technology & Engineering
  'Frontend Development',
  'Backend Development',
  'Full Stack Development',
  'Mobile Development',
  'DevOps',
  'Cloud Computing',
  'Artificial Intelligence',
  'Machine Learning',
  'Data Science',
  'Cybersecurity',
  'Blockchain',
  'UI/UX Design',
  'Software Architecture',
  'Product Management',
  'Project Management',

  // Business & Finance
  'Entrepreneurship',
  'Startup Culture',
  'Investment',
  'Financial Planning',
  'Marketing',
  'Digital Marketing',
  'Content Marketing',
  'Sales',
  'Business Strategy',
  'Consulting',
  'E-commerce',
  'Fintech',

  // Creative & Design
  'Graphic Design',
  'Web Design',
  'Photography',
  'Video Production',
  'Animation',
  'Creative Writing',
  'Content Creation',
  'Branding',
  'Art',
  'Music',

  // Industry Specific
  'Healthcare',
  'Education',
  'Legal',
  'Real Estate',
  'Automotive',
  'Manufacturing',
  'Retail',
  'Hospitality',
  'Food & Beverage',
  'Fashion',
  'Sports',
  'Gaming',

  // Skills & Methodologies
  'Agile Methodology',
  'Leadership',
  'Team Management',
  'Public Speaking',
  'Networking',
  'Remote Work',
  'Freelancing',
  'Career Development',
  'Learning & Development',
  'Innovation',

  // Emerging Technologies
  'Web3',
  'Metaverse',
  'IoT',
  'AR/VR',
  'Robotics',
  'Automation',
  'SaaS',
  'APIs',
  'Microservices',
  'Progressive Web Apps',

  // Personal Development
  'Productivity',
  'Time Management',
  'Work-Life Balance',
  'Mental Health',
  'Wellness',
  'Travel',
  'Languages',
  'Reading',
  'Podcasting',
  'Volunteering',
];

// Grouped interests for better UI sections
export const INTERESTS_GROUPS: { title: string; items: string[] }[] = [
  {
    title: 'Technology & Engineering',
    items: [
      'Frontend Development',
      'Backend Development',
      'Full Stack Development',
      'Mobile Development',
      'DevOps',
      'Cloud Computing',
      'Artificial Intelligence',
      'Machine Learning',
      'Data Science',
      'Cybersecurity',
      'Blockchain',
      'UI/UX Design',
      'Software Architecture',
      'Product Management',
      'Project Management',
    ],
  },
  {
    title: 'Business & Finance',
    items: [
      'Entrepreneurship',
      'Startup Culture',
      'Investment',
      'Financial Planning',
      'Marketing',
      'Digital Marketing',
      'Content Marketing',
      'Sales',
      'Business Strategy',
      'Consulting',
      'E-commerce',
      'Fintech',
    ],
  },
  {
    title: 'Creative & Design',
    items: [
      'Graphic Design',
      'Web Design',
      'Photography',
      'Video Production',
      'Animation',
      'Creative Writing',
      'Content Creation',
      'Branding',
      'Art',
      'Music',
    ],
  },
  {
    title: 'Industry Domains',
    items: [
      'Healthcare',
      'Education',
      'Legal',
      'Real Estate',
      'Automotive',
      'Manufacturing',
      'Retail',
      'Hospitality',
      'Food & Beverage',
      'Fashion',
      'Sports',
      'Gaming',
    ],
  },
  {
    title: 'Skills & Methods',
    items: [
      'Agile Methodology',
      'Leadership',
      'Team Management',
      'Public Speaking',
      'Networking',
      'Remote Work',
      'Freelancing',
      'Career Development',
      'Learning & Development',
      'Innovation',
    ],
  },
  {
    title: 'Emerging Tech',
    items: [
      'Web3',
      'Metaverse',
      'IoT',
      'AR/VR',
      'Robotics',
      'Automation',
      'SaaS',
      'APIs',
      'Microservices',
      'Progressive Web Apps',
    ],
  },
  {
    title: 'Personal Development',
    items: [
      'Productivity',
      'Time Management',
      'Work-Life Balance',
      'Mental Health',
      'Wellness',
      'Travel',
      'Languages',
      'Reading',
      'Podcasting',
      'Volunteering',
    ],
  },
];

export const INDUSTRY_OPTIONS = [
  'Technology',
  'Healthcare',
  'Finance & Banking',
  'Education',
  'Manufacturing',
  'Retail',
  'Real Estate',
  'Consulting',
  'Media & Entertainment',
  'Government',
  'Non-profit',
  'Automotive',
  'Energy',
  'Telecommunications',
  'Food & Beverage',
  'Fashion',
  'Sports & Recreation',
  'Transportation',
  'Construction',
  'Agriculture',
  'Legal Services',
  'Insurance',
  'Hospitality & Tourism',
  'Marketing & Advertising',
  'Aerospace',
  'Other',
];

export const EDUCATION_OPTIONS = [
  'High School',
  'Associate Degree',
  "Bachelor's Degree",
  "Master's Degree",
  'PhD',
  'Professional Certification',
  'Bootcamp',
  'Self-taught',
  'Trade School',
  'Other',
];

export const YEARS_OF_EXPERIENCE_OPTIONS = [
  { value: 0, label: 'No experience' },
  { value: 1, label: '1 year' },
  { value: 2, label: '2 years' },
  { value: 3, label: '3 years' },
  { value: 4, label: '4 years' },
  { value: 5, label: '5 years' },
  { value: 6, label: '6-10 years' },
  { value: 10, label: '10+ years' },
  { value: 15, label: '15+ years' },
  { value: 20, label: '20+ years' },
];
